### PR TITLE
Adds Ruby 3.1 and 3.2 to the CI matrix

### PR DESCRIPTION
**Pull request by petergoldstein**
Also updates the checkout and cache action versions to be current.

### CODE REVIEW

**Comment by tarcieri** [comment]
@petergoldstein can you remove `head`? I'm fine with adding the released versions, but `head` has the possibility of introducing unrelated breakages

**Comment by petergoldstein** [comment]
Sure @tarcieri .  Removed.

**Comment by petergoldstein** [comment]
@tarcieri Currently failing on Windows Ruby 3.2 builds, because that image isn't yet available.  Otherwise it's green

A recent Bundler version release required me to fix the bundler version, to support the wide range of Rubies in CI.

**Comment by dentarg** [comment]
> A recent Bundler version release required me to fix the bundler version, to support the wide range of Rubies in CI.

I think you can drop that, it has been addressed with https://github.com/ruby/setup-ruby/releases/tag/v1.129.0 in setup-ruby

**Comment by petergoldstein** [comment]
@dentarg Thanks. I'll try dropping it and see if the issue is resolved.

**Comment by tarcieri** [comment]
Still getting:

> Error: Unknown version 3.2 for ruby on windows-2022

**Comment by dentarg** [comment]
Yes, those haven't been built yet, https://github.com/puma/puma/pull/3049#issuecomment-1364708874

**Comment by tarcieri** [comment]
Perhaps just add 3.1 for now and then circle back on 3.2 when the images are available?

**Comment by petergoldstein** [comment]
@tarcieri I just added an exclude line for the Ruby 3.2 / Windows combination and now everything runs green.  Once the image is available that exclude line can just be removed.

**Review by tarcieri — APPROVED** [review]
Cool, that works for now, thanks!

**Pull request merged**
