### PR TITLE
Migrate to GH Actions

### PR DESCRIPTION
**Pull request by ixti**
* Add GH Actions workflow
* Remove Travis CI
* Update list of supported Ruby versions in README
* Test against truffleruby (overtakes #20)

### CODE REVIEW

**Comment by tarcieri** [comment]
Hrmm, looks like the (existing) Travis CI config is broken or something?

Perhaps it's time to switch to GitHub Actions...

**Comment by ixti** [comment]
@tarcieri I'm fine either way, but GH actions are ugly IMO :D

**Comment by ixti** [comment]
I'd propose to switch to GitLab :rofl:

**Comment by ixti** [comment]
In any case, if GH Actions is the way you want to go - I'm happy to assist. Will try to come with another PR for that.

**Comment by ixti** [comment]
@tarcieri I've replaced Travis with GH Actions. Will look like this:

---

image

**Comment by ixti** [comment]
With last commit workflow looks like this:

---

image

**Comment by tarcieri** [comment]
Merged and running now: https://github.com/RubyCrypto/ed25519/actions/runs/79317293

**Comment by ixti** [comment]
Awesome! Thank you!

**Pull request merged**
